# Generated by Django 4.1.5 on 2023-01-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_category_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.BigIntegerField()),
                ('about', models.TextField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(upload_to='')),
            ],
        ),
    ]
